"""Maps a DoclingDocument (docling-core) directly into a validated
ingestion_bench.canonical.CanonicalDocument.

This is the ONLY module besides adapter.py that imports Docling/docling-core
types. Nothing here reads reference_manifest.json or any other benchmark
ground truth -- the mapper's only job is to faithfully represent what
Docling actually reported, never what a benchmark expects it to report.

Docling -> Canonical mapping table (see also the report generated by
scripts/run_docling_standard.py for a live, per-fixture accounting):

    DoclingDocument.pages[page_no]        -> CanonicalUnit
        (PDF/PPTX only -- Docling exposes no page/slide geometry for DOCX;
        see _build_units' docstring for the documented DOCX fallback)
    TitleItem / SectionHeaderItem         -> CanonicalHeading
    TextItem (label TEXT/PARAGRAPH)       -> CanonicalParagraph
    TextItem (label FORMULA/CODE)         -> CanonicalParagraph
        (reduced fidelity: canonical has no dedicated formula/code type;
        recorded as a "reduced_fidelity_mapping" diagnostic)
    TextItem (label PAGE_HEADER/FOOTER/FOOTNOTE) -> skipped ("furniture")
    ListItem                              -> CanonicalListItem
    TextItem referenced by PictureItem.captions -> CanonicalCaption
    TableItem                             -> CanonicalTable / CanonicalTableCell
    PictureItem (with retrievable image bytes)  -> CanonicalPicture
    TextItem whose parent is a PictureItem, and that is NOT that picture's
        caption                            -> OcrAnnotation (derivation=
        "extracted") targeting the picture -- see _map_picture_ocr_children's
        docstring for exactly what evidence this relies on and its limits.
    every other DocItemLabel (DOCUMENT_INDEX, CHECKBOX_*, FORM,
        KEY_VALUE_REGION, GRADING_SCALE, HANDWRITTEN_TEXT, EMPTY_VALUE,
        REFERENCE, FIELD_*, MARKER, CHART as a body item rather than a
        picture) -> skipped ("unsupported_label")

No ImageDescriptionAnnotation, VisualFactAnnotation, SemanticClaimAnnotation,
or model-derived DiagramNode/EdgeAnnotation is ever produced here -- Stage 5A
creates no model-derived content of any kind.
"""

from __future__ import annotations

from dataclasses import dataclass, field as dataclass_field

from docling_core.types.doc import BoundingBox as DoclingBoundingBox
from docling_core.types.doc import CoordOrigin
from docling_core.types.doc.document import DoclingDocument, ListItem as DoclingListItem, PictureItem as DoclingPictureItem, TableItem as DoclingTableItem
from docling_core.types.doc.labels import DocItemLabel, GroupLabel

from ingestion_bench.canonical import (
    BoundingBox,
    CanonicalCaption,
    CanonicalDocument,
    CanonicalHeading,
    CanonicalListItem,
    CanonicalParagraph,
    CanonicalPicture,
    CanonicalTable,
    CanonicalTableCell,
    CanonicalUnit,
    OcrAnnotation,
    ProvenanceEntry,
)
from ingestion_bench.canonical.hashing import stable_element_id

from .diagnostics import DiagnosticCollector

_HEADING_LABELS = {DocItemLabel.TITLE, DocItemLabel.SECTION_HEADER}
_PARAGRAPH_LABELS = {DocItemLabel.TEXT, DocItemLabel.PARAGRAPH}
_REDUCED_FIDELITY_PARAGRAPH_LABELS = {DocItemLabel.FORMULA, DocItemLabel.CODE}
_FURNITURE_LABELS = {DocItemLabel.PAGE_HEADER, DocItemLabel.PAGE_FOOTER, DocItemLabel.FOOTNOTE}
_LIST_GROUP_LABELS = {GroupLabel.LIST, GroupLabel.ORDERED_LIST}


@dataclass
class DocxPageFallback:
    """Docling's standard pipeline exposes NO page geometry for DOCX
    (DoclingDocument.pages is empty and every item's .prov is []) -- this
    is a genuine Docling limitation, not an adapter gap. Per the Stage 5A
    scope gate, the canonical contract may not be altered, and
    CanonicalUnit.width/height must be > 0 (never a fabricated Letter/A4
    default). adapter.py reads the SOURCE FILE'S OWN section geometry via
    python-docx (already a repository dependency, used only for this one
    structural field, never for content) and supplies it here. This is a
    real, file-declared value -- not invented -- but it did not come from
    Docling, and every DOCX conversion records a diagnostic saying so."""

    width_pt: float
    height_pt: float


@dataclass
class MappingResult:
    canonical_document: CanonicalDocument | None
    diagnostics: list
    mapped_counts: dict
    skipped_counts: dict = dataclass_field(default_factory=dict)


def _convert_bbox(docling_bbox: DoclingBoundingBox, page_height: float, coordinate_unit: str) -> BoundingBox:
    """Docling's PDF/PPTX bounding boxes use a BOTTOM-LEFT origin (y
    increases upward, matching PDF's native coordinate space) -- never
    copied as-is. Normalized here into the canonical model's top-left
    origin (y increases downward): x is unchanged (origin flip is only
    ever in y), y0 = page_height - top, y1 = page_height - bottom."""
    if docling_bbox.coord_origin == CoordOrigin.BOTTOMLEFT:
        y0 = page_height - docling_bbox.t
        y1 = page_height - docling_bbox.b
    else:
        y0, y1 = docling_bbox.t, docling_bbox.b
    return BoundingBox(
        x0=docling_bbox.l, y0=y0, x1=docling_bbox.r, y1=y1,
        coordinate_unit=coordinate_unit, coordinate_origin="top-left",
    )


class DoclingToCanonicalMapper:
    """One mapper instance maps exactly one DoclingDocument. Not reused
    across documents -- construct a fresh instance per conversion."""

    def __init__(
        self,
        *,
        doc_id: str,
        source_format: str,
        source_filename: str,
        source_relative_path: str,
        source_sha256: str,
        docx_page_fallback: DocxPageFallback | None = None,
    ) -> None:
        self.doc_id = doc_id
        self.source_format = source_format
        self.source_filename = source_filename
        self.source_relative_path = source_relative_path
        self.source_sha256 = source_sha256
        self.docx_page_fallback = docx_page_fallback

        self.diagnostics = DiagnosticCollector()
        self.mapped_counts: dict[str, int] = {}
        self.skipped_counts: dict[str, int] = {}

        self._units: dict[int, CanonicalUnit] = {}
        self._page_height_by_unit: dict[int, float] = {}
        self._coordinate_unit = {"pdf": "pt", "pptx": "emu", "docx": "pt"}[source_format]
        self._order_counters: dict[int, int] = {}

        self.headings: list[CanonicalHeading] = []
        self.paragraphs: list[CanonicalParagraph] = []
        self.list_items: list[CanonicalListItem] = []
        self.captions: list[CanonicalCaption] = []
        self.tables: list[CanonicalTable] = []
        self.pictures: list[CanonicalPicture] = []
        self.annotations: list = []
        self.provenance: list[ProvenanceEntry] = []

    def _record(self, category: str, message: str, **kwargs) -> None:
        self.diagnostics.record(category, message, **kwargs)

    def _bump_mapped(self, kind: str) -> None:
        self.mapped_counts[kind] = self.mapped_counts.get(kind, 0) + 1

    def _bump_skipped(self, reason: str) -> None:
        self.skipped_counts[reason] = self.skipped_counts.get(reason, 0) + 1

    def _next_order_index(self, unit_index: int) -> int:
        current = self._order_counters.get(unit_index, 0)
        self._order_counters[unit_index] = current + 1
        return current

    # --- units ---------------------------------------------------------

    def build_units(self, docling_doc: DoclingDocument) -> bool:
        """Populates self._units. Returns False (and records an error
        diagnostic) if no usable unit geometry could be established at
        all -- callers must treat that as a failed conversion, never
        construct a CanonicalDocument with zero units."""
        if docling_doc.pages:
            unit_type = "slide" if self.source_format == "pptx" else "page"
            for page_no, page in sorted(docling_doc.pages.items()):
                if page.size is None or page.size.width <= 0 or page.size.height <= 0:
                    self._record(
                        "missing_geometry",
                        f"page_no={page_no} has no usable size; unit skipped",
                        severity="error", unit_index=page_no - 1, affects_fidelity=True,
                    )
                    continue
                unit_index = page_no - 1  # Docling page_no is 1-based; canonical unit_index is 0-based
                self._units[unit_index] = CanonicalUnit(
                    unit_index=unit_index, unit_type=unit_type,
                    width=page.size.width, height=page.size.height,
                    coordinate_unit=self._coordinate_unit, coordinate_origin="top-left",
                )
                self._page_height_by_unit[unit_index] = page.size.height
            if not self._units:
                self._record("missing_geometry", "no page reported usable geometry", severity="error", affects_fidelity=True)
                return False
            return True

        # DOCX: Docling reports no pages at all.
        if self.docx_page_fallback is None:
            self._record(
                "missing_geometry",
                "DOCX has no Docling page geometry and no docx_page_fallback was supplied",
                severity="error", affects_fidelity=True,
            )
            return False
        self._record(
            "docx_pagination_unavailable",
            "Docling's standard pipeline exposes no page/pagination geometry for "
            "DOCX; the whole document is mapped as a single CanonicalUnit whose "
            "width/height were read from the source file's own section "
            "properties via python-docx (not from Docling), and true page-break "
            "positions are unrecoverable -- this is a real loss of source "
            "pagination structure, not merely an informational note",
            severity="info", unit_index=0, affects_fidelity=True,
        )
        self._units[0] = CanonicalUnit(
            unit_index=0, unit_type="page",
            width=self.docx_page_fallback.width_pt, height=self.docx_page_fallback.height_pt,
            coordinate_unit="pt", coordinate_origin="top-left",
        )
        self._page_height_by_unit[0] = self.docx_page_fallback.height_pt
        return True

    # --- element-level helpers ------------------------------------------

    def _resolve_unit_index(self, item, *, where: str) -> int | None:
        prov = getattr(item, "prov", None)
        if prov:
            unit_index = prov[0].page_no - 1
            if unit_index not in self._units:
                self._record("missing_provenance", f"{where}: page_no {prov[0].page_no} has no matching unit", severity="warning", docling_self_ref=item.self_ref, affects_fidelity=True)
                return None
            return unit_index
        if self.source_format == "docx" and 0 in self._units:
            return 0
        self._record("missing_provenance", f"{where}: no provenance available", severity="warning", docling_self_ref=item.self_ref, affects_fidelity=True)
        return None

    def _bbox_for(self, item, unit_index: int):
        prov = getattr(item, "prov", None)
        if not prov or prov[0].bbox is None:
            return None
        try:
            return _convert_bbox(prov[0].bbox, self._page_height_by_unit[unit_index], self._coordinate_unit)
        except Exception as exc:  # malformed geometry -- degrade, never crash the whole conversion
            self._record("malformed_geometry", f"bbox conversion failed: {exc}", severity="warning", docling_self_ref=item.self_ref, unit_index=unit_index, affects_fidelity=True)
            return None

    # --- headings / paragraphs / list items ------------------------------

    def map_heading(self, item) -> str | None:
        unit_index = self._resolve_unit_index(item, where="heading")
        if unit_index is None:
            self._bump_skipped("missing_provenance")
            return None
        order_index = self._next_order_index(unit_index)
        block_id = stable_element_id(self.doc_id, "heading", unit_index, order_index=order_index, discriminator=item.self_ref)
        level = getattr(item, "level", None) or 1
        bbox = self._bbox_for(item, unit_index)
        self.headings.append(CanonicalHeading(block_id=block_id, unit_index=unit_index, order_index=order_index, text=item.text, bbox=bbox, level=level))
        self.provenance.append(ProvenanceEntry(element_id=block_id, unit_index=unit_index, order_index=order_index, bbox=bbox, source_element_ref=item.self_ref, source_locator={"docling_label": str(item.label)}))
        self._bump_mapped("heading")
        return block_id

    def map_paragraph(self, item, *, reduced_fidelity: bool = False) -> str | None:
        unit_index = self._resolve_unit_index(item, where="paragraph")
        if unit_index is None:
            self._bump_skipped("missing_provenance")
            return None
        order_index = self._next_order_index(unit_index)
        block_id = stable_element_id(self.doc_id, "paragraph", unit_index, order_index=order_index, discriminator=item.self_ref)
        bbox = self._bbox_for(item, unit_index)
        self.paragraphs.append(CanonicalParagraph(block_id=block_id, unit_index=unit_index, order_index=order_index, text=item.text, bbox=bbox))
        self.provenance.append(ProvenanceEntry(element_id=block_id, unit_index=unit_index, order_index=order_index, bbox=bbox, source_element_ref=item.self_ref, source_locator={"docling_label": str(item.label)}))
        self._bump_mapped("paragraph")
        if reduced_fidelity:
            self._record("reduced_fidelity_mapping", f"label={item.label} has no dedicated canonical type; mapped as CanonicalParagraph", severity="info", docling_self_ref=item.self_ref, unit_index=unit_index, affects_fidelity=True)
        return block_id

    def map_list_item(self, item, docling_doc: DoclingDocument, block_id_by_self_ref: dict) -> None:
        unit_index = self._resolve_unit_index(item, where="list_item")
        if unit_index is None:
            self._bump_skipped("missing_provenance")
            return
        order_index = self._next_order_index(unit_index)
        block_id = stable_element_id(self.doc_id, "list_item", unit_index, order_index=order_index, discriminator=item.self_ref)
        bbox = self._bbox_for(item, unit_index)

        indent_level, list_group_ref, parent_group_owner_ref = _walk_list_ancestry(item, docling_doc)
        list_id = stable_element_id(self.doc_id, "list", unit_index, discriminator=list_group_ref or item.self_ref)
        parent_block_id = block_id_by_self_ref.get(parent_group_owner_ref) if parent_group_owner_ref else None
        if indent_level == 0 and list_group_ref is None:
            self._record("missing_provenance", "list item has no enclosing list group; indent_level defaulted to 0", severity="warning", docling_self_ref=item.self_ref, unit_index=unit_index, affects_fidelity=True)

        self.list_items.append(CanonicalListItem(
            block_id=block_id, unit_index=unit_index, order_index=order_index, text=item.text, bbox=bbox,
            list_id=list_id, indent_level=indent_level, parent_block_id=parent_block_id,
        ))
        self.provenance.append(ProvenanceEntry(element_id=block_id, unit_index=unit_index, order_index=order_index, bbox=bbox, source_element_ref=item.self_ref, source_locator={"docling_label": str(item.label)}))
        block_id_by_self_ref[item.self_ref] = block_id
        self._bump_mapped("list_item")

    # --- tables ------------------------------------------------------------

    def map_table(self, item: DoclingTableItem) -> None:
        unit_index = self._resolve_unit_index(item, where="table")
        if unit_index is None:
            self._bump_skipped("missing_provenance")
            return
        order_index = self._next_order_index(unit_index)
        table_id = stable_element_id(self.doc_id, "table", unit_index, order_index=order_index, discriminator=item.self_ref)
        bbox = self._bbox_for(item, unit_index)

        n_rows, n_cols = item.data.num_rows, item.data.num_cols
        cells: list[CanonicalTableCell] = []
        for cell in item.data.table_cells:
            if not (0 <= cell.start_row_offset_idx < n_rows) or not (0 <= cell.start_col_offset_idx < n_cols):
                self._record("malformed_table_cell", f"cell row={cell.start_row_offset_idx} col={cell.start_col_offset_idx} out of bounds for {n_rows}x{n_cols}", severity="warning", docling_self_ref=item.self_ref, unit_index=unit_index, affects_fidelity=True)
                continue
            if cell.start_row_offset_idx + cell.row_span > n_rows or cell.start_col_offset_idx + cell.col_span > n_cols:
                self._record("malformed_table_cell", f"cell row={cell.start_row_offset_idx} col={cell.start_col_offset_idx} span exceeds {n_rows}x{n_cols}", severity="warning", docling_self_ref=item.self_ref, unit_index=unit_index, affects_fidelity=True)
                continue
            cells.append(CanonicalTableCell(
                row=cell.start_row_offset_idx, col=cell.start_col_offset_idx,
                row_span=cell.row_span, col_span=cell.col_span,
                text=cell.text, is_header=bool(cell.column_header or cell.row_header),
            ))

        self.tables.append(CanonicalTable(table_id=table_id, unit_index=unit_index, order_index=order_index, bbox=bbox, n_rows=n_rows, n_cols=n_cols, cells=cells))
        self.provenance.append(ProvenanceEntry(element_id=table_id, unit_index=unit_index, order_index=order_index, bbox=bbox, source_element_ref=item.self_ref, source_locator={"docling_label": str(item.label)}))
        self._bump_mapped("table")

    # --- pictures + captions -------------------------------------------------

    def map_picture(self, item: DoclingPictureItem, docling_doc: DoclingDocument, image_saver) -> str | None:
        """Returns the mapped picture_id, or None if the picture was
        skipped (e.g. no retrievable image bytes). image_saver(picture_id,
        pil_image) -> artifact_ref, content_sha256."""
        unit_index = self._resolve_unit_index(item, where="picture")
        if unit_index is None:
            self._bump_skipped("missing_provenance")
            return None

        try:
            pil_image = item.get_image(docling_doc)
        except Exception as exc:
            pil_image = None
            self._record("missing_picture_bytes", f"get_image() raised: {exc}", severity="warning", docling_self_ref=item.self_ref, unit_index=unit_index, affects_fidelity=True)

        if pil_image is None:
            self._record("missing_picture_bytes", "Docling identified a picture but provided no retrievable image bytes; CanonicalPicture.content_sha256 is required, so this picture (and any caption/OCR text pointed at it) is skipped rather than invented", severity="warning", docling_self_ref=item.self_ref, unit_index=unit_index, affects_fidelity=True)
            self._bump_skipped("missing_picture_bytes")
            return None

        picture_id = stable_element_id(self.doc_id, "picture", unit_index, discriminator=item.self_ref)
        artifact_ref, content_sha256 = image_saver(picture_id, pil_image)
        bbox = self._bbox_for(item, unit_index)

        self.pictures.append(CanonicalPicture(picture_id=picture_id, unit_index=unit_index, bbox=bbox, content_sha256=content_sha256, artifact_ref=artifact_ref))
        self._bump_mapped("picture")
        return picture_id

    def finalize_picture_provenance(self, item: DoclingPictureItem, picture_id: str) -> None:
        """CanonicalPicture has no order_index field of its own (Stage 2
        contract) -- reading-order position for a picture is carried
        exclusively via its ProvenanceEntry.order_index (the same
        fallback the frozen chunker already reads, see
        chunking/chunker.py::_build_ordered_elements). Called from the
        main traversal loop, at the picture's real sequential position --
        never from the pre-pass that creates the CanonicalPicture itself,
        which runs before body ordering is known."""
        unit_index = self._resolve_unit_index(item, where="picture-provenance")
        if unit_index is None:
            return
        order_index = self._next_order_index(unit_index)
        bbox = self._bbox_for(item, unit_index)
        self.provenance.append(ProvenanceEntry(element_id=picture_id, unit_index=unit_index, order_index=order_index, bbox=bbox, source_element_ref=item.self_ref, source_locator={"docling_label": str(item.label)}))

    def map_caption(self, text_item, picture_id: str, unit_index: int) -> None:
        order_index = self._next_order_index(unit_index)
        block_id = stable_element_id(self.doc_id, "caption", unit_index, order_index=order_index, discriminator=text_item.self_ref)
        bbox = self._bbox_for(text_item, unit_index)
        self.captions.append(CanonicalCaption(block_id=block_id, unit_index=unit_index, order_index=order_index, text=text_item.text, bbox=bbox, target_picture_id=picture_id))
        self.provenance.append(ProvenanceEntry(element_id=block_id, unit_index=unit_index, order_index=order_index, bbox=bbox, source_element_ref=text_item.self_ref, source_locator={"docling_label": str(text_item.label)}))
        self._bump_mapped("caption")

    def map_picture_ocr_child(self, text_item, picture_id: str, unit_index: int, *, ocr_sequence: int) -> None:
        """A TextItem nested directly under a PictureItem (and not that
        picture's caption) is the only OCR-origin signal Docling's public
        API exposes in this version: individual items carry no
        confidence/source-engine field distinguishing OCR text from
        native text (TextItem.source is always []). Structural nesting
        under a PictureItem is used instead -- native page text is never a
        child of a picture, so this is real (if indirect) evidence, not a
        guess based on which fixture is being processed. Text that Docling
        places at body level (e.g. the scanned-PDF fixture, where the
        whole page is one OCR pass with no picture wrapper) has NO such
        signal and is mapped as plain CanonicalParagraph instead -- see
        map_paragraph for that case; no diagnostic is emitted for it since
        that text is not lost, only not distinguished as OCR-origin.

        Every OcrAnnotation gets a matching ProvenanceEntry whenever
        Docling actually supplies evidence for it (bbox via text_item.prov,
        self_ref, an ocr_sequence disambiguating multiple OCR lines under
        the same picture) -- ProvenanceEntry.element_id may legitimately
        resolve to an annotation_id (see
        canonical/model.py::_validate_provenance_element_ids), so this adds
        no new canonical concept. No bbox or provenance is fabricated when
        Docling provides none (bbox stays None in that case)."""
        annotation_id = stable_element_id(self.doc_id, "annotation:ocr", unit_index, discriminator=f"{picture_id}:{text_item.self_ref}")
        self.annotations.append(OcrAnnotation(
            annotation_id=annotation_id, target_ref=picture_id, unit_index=unit_index,
            extraction_method="docling_rapidocr", text=text_item.text,
        ))
        bbox = self._bbox_for(text_item, unit_index)
        self.provenance.append(ProvenanceEntry(
            element_id=annotation_id, unit_index=unit_index, order_index=None, bbox=bbox,
            source_element_ref=text_item.self_ref,
            source_locator={
                "docling_label": str(text_item.label),
                "extraction_method": "docling_rapidocr",
                "ocr_sequence": ocr_sequence,
            },
        ))
        self._bump_mapped("ocr_annotation")

    # --- full-document orchestration --------------------------------------

    def map_document(self, docling_doc: DoclingDocument, image_saver) -> None:
        """Walks the whole DoclingDocument exactly ONCE, in Docling's own
        deterministic traversal order (iterate_items()), and populates
        every canonical collection. order_index is assigned strictly in
        this single pass for every element type -- headings, paragraphs,
        list items, tables, pictures, and captions alike -- so reading
        order is never scrambled by handling some element types in a
        separate pre/post pass. image_saver(picture_id, PIL.Image) ->
        (artifact_ref, content_sha256) is injected so this method has no
        filesystem dependency of its own -- unit tests can pass a fake
        in-memory saver."""
        pictures_by_self_ref = {p.self_ref: p for p in docling_doc.pictures}
        picture_caption_owner: dict[str, DoclingPictureItem] = {}
        table_caption_refs: set[str] = set()
        for picture in docling_doc.pictures:
            for ref in getattr(picture, "captions", None) or []:
                picture_caption_owner[ref.cref] = picture
        for table in docling_doc.tables:
            for ref in getattr(table, "captions", None) or []:
                table_caption_refs.add(ref.cref)

        # Image bytes must be fetched before the main pass (picture_id is
        # needed to resolve caption/OCR-child ownership as we reach those
        # items in order) -- but this pre-pass never assigns order_index,
        # only identity; see finalize_picture_provenance for where a
        # picture's ProvenanceEntry.order_index is actually set.
        picture_id_by_self_ref: dict[str, str] = {}
        for picture in docling_doc.pictures:
            picture_id = self.map_picture(picture, docling_doc, image_saver)
            if picture_id is not None:
                picture_id_by_self_ref[picture.self_ref] = picture_id

        # DoclingDocument.iterate_items() does NOT descend into a picture's
        # non-caption children (verified empirically against docling
        # 2.114.0/docling-core 2.87.1: a picture's OCR-detected text lines
        # are never yielded by iterate_items(), only its caption is) --
        # so OCR-child text must be found by scanning doc.texts directly,
        # not the main traversal below. OcrAnnotation has no order_index
        # field, so this pass does not need to run in reading order.
        ocr_child_self_refs: set[str] = set()
        ocr_sequence_by_picture: dict[str, int] = {}
        for text_item in docling_doc.texts:
            parent_ref = text_item.parent.cref if text_item.parent else None
            if parent_ref not in pictures_by_self_ref:
                continue
            if text_item.self_ref in picture_caption_owner:
                continue  # this picture-child is its caption, not OCR text
            picture_id = picture_id_by_self_ref.get(parent_ref)
            unit_index = self._resolve_unit_index(pictures_by_self_ref[parent_ref], where="picture-ocr-child") if picture_id else None
            ocr_child_self_refs.add(text_item.self_ref)
            if picture_id is None or unit_index is None:
                self._record("skipped_item", "OCR-child text targets a picture that was skipped", severity="warning", docling_self_ref=text_item.self_ref, affects_fidelity=True)
                self._bump_skipped("ocr_target_picture_unavailable")
                continue
            ocr_sequence_by_picture[parent_ref] = ocr_sequence_by_picture.get(parent_ref, 0) + 1
            self.map_picture_ocr_child(text_item, picture_id, unit_index, ocr_sequence=ocr_sequence_by_picture[parent_ref])

        block_id_by_self_ref: dict[str, str] = {}
        for item, _level in docling_doc.iterate_items():
            self_ref = getattr(item, "self_ref", None)
            if self_ref is None:
                continue
            label = getattr(item, "label", None)
            parent_ref = item.parent.cref if getattr(item, "parent", None) else None

            if isinstance(item, DoclingPictureItem):
                picture_id = picture_id_by_self_ref.get(self_ref)
                if picture_id is not None:
                    self.finalize_picture_provenance(item, picture_id)
                continue

            if isinstance(item, DoclingTableItem):
                self.map_table(item)
                continue

            if self_ref in picture_caption_owner:
                picture = picture_caption_owner[self_ref]
                picture_id = picture_id_by_self_ref.get(picture.self_ref)
                unit_index = self._resolve_unit_index(picture, where="picture-caption")
                if picture_id is None or unit_index is None:
                    self._record("ambiguous_caption_relationship", "caption target picture was skipped; caption dropped", severity="warning", docling_self_ref=self_ref, affects_fidelity=True)
                    self._bump_skipped("ambiguous_caption_relationship")
                else:
                    self.map_caption(item, picture_id, unit_index)
                continue

            if self_ref in table_caption_refs:
                self.map_paragraph(item, reduced_fidelity=True)
                self._record("reduced_fidelity_mapping", "table caption has no dedicated canonical representation; mapped as CanonicalParagraph", severity="info", docling_self_ref=self_ref, affects_fidelity=True)
                continue

            if parent_ref in pictures_by_self_ref:
                # Already handled by the dedicated doc.texts scan above
                # (iterate_items() does not reliably surface these); skip
                # here so it is never double-processed if some other
                # format's traversal does yield it.
                continue

            if isinstance(item, DoclingListItem):
                self.map_list_item(item, docling_doc, block_id_by_self_ref)
            elif label in _HEADING_LABELS:
                block_id = self.map_heading(item)
                if block_id is not None:
                    block_id_by_self_ref[self_ref] = block_id
            elif label in _PARAGRAPH_LABELS:
                block_id = self.map_paragraph(item)
                if block_id is not None:
                    block_id_by_self_ref[self_ref] = block_id
            elif label in _REDUCED_FIDELITY_PARAGRAPH_LABELS:
                self.map_paragraph(item, reduced_fidelity=True)
            elif label in _FURNITURE_LABELS:
                self._record("skipped_furniture", f"label={label} treated as furniture, not body content", severity="info", docling_self_ref=self_ref)
                self._bump_skipped("furniture")
            elif label == DocItemLabel.CAPTION:
                self._record("ambiguous_caption_relationship", "caption-labeled text has no picture/table owner", severity="warning", docling_self_ref=self_ref, affects_fidelity=True)
                self._bump_skipped("ambiguous_caption_relationship")
            else:
                self._record("unsupported_label", f"label={label} type={type(item).__name__} has no canonical mapping", severity="info", docling_self_ref=self_ref, affects_fidelity=True)
                self._bump_skipped("unsupported_label")

    # --- final assembly --------------------------------------------------

    def build(self) -> CanonicalDocument | None:
        try:
            return CanonicalDocument(
                doc_id=self.doc_id, source_format=self.source_format,
                source_filename=self.source_filename, source_relative_path=self.source_relative_path,
                source_sha256=self.source_sha256,
                units=sorted(self._units.values(), key=lambda u: u.unit_index),
                headings=self.headings, paragraphs=self.paragraphs, list_items=self.list_items,
                captions=self.captions, tables=self.tables, pictures=self.pictures,
                annotations=self.annotations, provenance=self.provenance,
            )
        except Exception as exc:
            self._record("canonical_document_construction_failed", str(exc), severity="error")
            return None


def _walk_list_ancestry(item: DoclingListItem, docling_doc: DoclingDocument) -> tuple[int, str | None, str | None]:
    """Returns (indent_level, outermost_list_group_self_ref, parent_owner_self_ref).

    indent_level is the count of ancestor GroupItems labeled LIST/ORDERED_LIST
    reachable by following .parent, walking THROUGH intervening ListItem
    ancestors (true nesting: item -> group -> ListItem -> group -> ...) --
    a real structural computation, not a guess. parent_owner_self_ref is
    the self_ref of the innermost ListItem ancestor encountered along that
    walk (exactly what CanonicalListItem.parent_block_id expects); None if
    no ListItem ancestor is ever encountered before the walk reaches
    something that is neither a list group nor a list item (e.g. a
    heading, or the body directly).
    """
    self_ref_to_listitem = {t.self_ref: t for t in docling_doc.texts if isinstance(t, DoclingListItem)}
    self_ref_to_group = {g.self_ref: g for g in docling_doc.groups}

    depth = 0
    outermost_group_ref: str | None = None
    parent_owner_ref: str | None = None
    innermost_recorded = False

    current_ref = item.parent.cref if item.parent else None
    while current_ref:
        if current_ref in self_ref_to_group:
            group = self_ref_to_group[current_ref]
            if group.label not in _LIST_GROUP_LABELS:
                break
            depth += 1
            outermost_group_ref = current_ref
            current_ref = group.parent.cref if group.parent else None
        elif current_ref in self_ref_to_listitem:
            if not innermost_recorded:
                parent_owner_ref = current_ref
                innermost_recorded = True
            current_ref = self_ref_to_listitem[current_ref].parent.cref if self_ref_to_listitem[current_ref].parent else None
        else:
            break

    return depth - 1 if depth > 0 else 0, outermost_group_ref, parent_owner_ref
